### ISSUE TITLE
Not opening sound files in SWFs

### ISSUE THREAD

**Issue by Zishan-Rahman** [flathub/com.jpexs.decompiler.flash#12]
Every time I try to open a sound file from a SWF file in this Flatpak, I get the following error message:
```
31/01/2022 23:13:15 SEVERE Uncaught exception in thread: AWT-EventQueue-0
java.lang.IllegalArgumentException: No line matching interface Clip is supported.
	at javax.sound.sampled.AudioSystem.getLine(AudioSystem.java:479)
	at com.jpexs.decompiler.flash.gui.SoundTagPlayer.<init>(SoundTagPlayer.java:95)
	at com.jpexs.decompiler.flash.gui.MainPanel.showPreview(MainPanel.java:3618)
	at com.jpexs.decompiler.flash.gui.MainPanel.reload(MainPanel.java:3780)
	at com.jpexs.decompiler.flash.gui.MainPanel.valueChanged(MainPanel.java:3329)
	at javax.swing.JTree.fireValueChanged(JTree.java:2934)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at com.jpexs.decompiler.flash.gui.MainPanel$1.setSelectionPaths(MainPanel.java:539)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at com.jpexs.decompiler.flash.gui.MainPanel$1.setSelectionPath(MainPanel.java:530)
	at javax.swing.JTree.setSelectionPath(JTree.java:1641)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3548)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6536)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I do not have this problem when I download the cross-platform zip version from GitHub and run the bash script.

For reference, I am running Linux Mint 20.3.

**Comment by Newbytee** [comment]
Could you mention (and preferably also link) a game whose sound files reproduce this issue

**Comment by Newbytee** [comment]
Never mind, can reproduce. Fix coming soon.

**Comment by Zishan-Rahman** [comment]
> Never mind, can reproduce. Fix coming soon.

Thanks! FTR I've had that problem with every sound file I've tried to load.

**Comment by Newbytee** [comment]
Hey again.

Sorry this took a while, I've had issues validating my fix due to what might be a PipeWire bug. Could you see if this works for you: https://github.com/flathub/com.jpexs.decompiler.flash/pull/14

**Comment by Zishan-Rahman** [comment]
> Hey again.
> 
> Sorry this took a while, I've had issues validating my fix due to what might be a PipeWire bug. Could you see if this works for you: #14 (use the test build the bot will create soon)

It works now. Thank you so much!
